// @generated by scripts/generate_contracts.py; DO NOT EDIT.
// Source: contracts/catalog/contract-vocabulary.v1.json

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum TerminalReason {
    RulesLoss,
    Concession,
    SimultaneousOutcome,
    RulesDraw,
    SpecifiedLoop,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum TruncationReason {
    DecisionLimit,
    RuleEventLimit,
    WallClockLimit,
    ResourceLimit,
    ExternalStop,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum PlayerResult {
    Win,
    Loss,
    Draw,
    Eliminated,
    Unresolved,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ZoneKind {
    Library,
    Hand,
    Battlefield,
    Graveyard,
    Exile,
    Stack,
    Command,
    Ante,
    Outside,
}

pub const STABLE_WIRE_ERROR_CODES: &[&str] = &[
    "decode.invalid_json",
    "decode.non_canonical_json",
    "encode.serialization",
    "semantic.decision",
    "semantic.decision_response",
    "semantic.observation",
    "semantic.information_state",
    "semantic.observed_event",
    "semantic.player_step",
    "semantic.episode_status",
    "semantic.replay_manifest",
    "semantic.replay",
    "fixture.unknown_contract",
];
