// @generated by scripts/generate_semantic_contract_catalog.py; DO NOT EDIT.
// Source: contracts/catalog/semantic-contracts.v1.json
//
// Manifest constants AND derived ID values for the runtime semantic
// catalog (spec §10). Rust const-evaluation cannot allocate, so the
// derived ID VALUES are checked in as canonical hex string constants
// and materialized deterministically through parse() accessors (no
// lazy statics — spec §10 bans hidden process state). The recompute KAT
// (semantic_catalog_kat.rs) re-derives every ID from these generated
// manifest constants via the §9 persistence functions and fails the
// build on drift. Hand-editing any constant is a gate violation.
#![allow(dead_code)] // hex constants and *_rules_contract_id accessors are KAT/test-only

use mtgml_model::{RulesContractIdV1, SemanticContractIdV1};

// synthetic_legacy_default
pub const SEMANTIC_CONTRACT_CATALOG_SYNTHETIC_LEGACY_DEFAULT_RULES_CONTRACT_HEX: &str =
    "19bac684b74115b4fab823dfae2d3e75c23ee24f78effe51e9f72a33d4a58521";
pub const SEMANTIC_CONTRACT_CATALOG_SYNTHETIC_LEGACY_DEFAULT_SEMANTIC_CONTRACT_HEX: &str =
    "66ccac959475370e641e853473cbdd7f88489399587794b43f66cfa0342b1be4";

pub fn synthetic_legacy_default_rules_manifest() -> mtgml_model::RulesContractManifestV1 {
    mtgml_model::RulesContractManifestV1 {
        rules_authority: mtgml_model::RulesAuthorityV1::SyntheticLegacy,
        capability_closure: None,
    }
}

pub fn synthetic_legacy_default_semantic_manifest() -> mtgml_model::SemanticContractManifestV1 {
    mtgml_model::SemanticContractManifestV1 {
        rules_contract_id: synthetic_legacy_default_rules_contract_id(),
        format_contract_id: None,
        content_contract_id: None,
    }
}

pub fn synthetic_legacy_default_rules_contract_id() -> RulesContractIdV1 {
    RulesContractIdV1::parse(SEMANTIC_CONTRACT_CATALOG_SYNTHETIC_LEGACY_DEFAULT_RULES_CONTRACT_HEX)
        .expect("generated canonical hex")
}

pub fn synthetic_legacy_default_semantic_contract_id() -> SemanticContractIdV1 {
    SemanticContractIdV1::parse(
        SEMANTIC_CONTRACT_CATALOG_SYNTHETIC_LEGACY_DEFAULT_SEMANTIC_CONTRACT_HEX,
    )
    .expect("generated canonical hex")
}

// magic_turn_structure_0_1_0
pub const SEMANTIC_CONTRACT_CATALOG_MAGIC_TURN_STRUCTURE_0_1_0_RULES_CONTRACT_HEX: &str =
    "92377633765924893ad9ca0102a07cdf2a8730526909b7d7b5e3059ae4487065";
pub const SEMANTIC_CONTRACT_CATALOG_MAGIC_TURN_STRUCTURE_0_1_0_SEMANTIC_CONTRACT_HEX: &str =
    "7e8f54f15bd27d16643422f6904a23ea2004cab1098b56f8cd842a2397ff42fe";

pub fn magic_turn_structure_0_1_0_rules_manifest() -> mtgml_model::RulesContractManifestV1 {
    mtgml_model::RulesContractManifestV1 {
        rules_authority: mtgml_model::RulesAuthorityV1::ComprehensiveRules {
            snapshot_id: "wotc-cr-2026-08-07-txt-20260819-sha256-4381ad1b39ab2c05f7d03633a20f711ed37277074d3266dcba5f38cbb527423f".to_owned(),
        },
        capability_closure: Some(vec![
            mtgml_model::CapabilityRequirementV1 {
                key: "rules/turn-structure".to_owned(),
                version: "0.1.0".to_owned(),
            },
        ]),
    }
}

pub fn magic_turn_structure_0_1_0_semantic_manifest() -> mtgml_model::SemanticContractManifestV1 {
    mtgml_model::SemanticContractManifestV1 {
        rules_contract_id: magic_turn_structure_0_1_0_rules_contract_id(),
        format_contract_id: None,
        content_contract_id: None,
    }
}

pub fn magic_turn_structure_0_1_0_rules_contract_id() -> RulesContractIdV1 {
    RulesContractIdV1::parse(
        SEMANTIC_CONTRACT_CATALOG_MAGIC_TURN_STRUCTURE_0_1_0_RULES_CONTRACT_HEX,
    )
    .expect("generated canonical hex")
}

pub fn magic_turn_structure_0_1_0_semantic_contract_id() -> SemanticContractIdV1 {
    SemanticContractIdV1::parse(
        SEMANTIC_CONTRACT_CATALOG_MAGIC_TURN_STRUCTURE_0_1_0_SEMANTIC_CONTRACT_HEX,
    )
    .expect("generated canonical hex")
}

// magic_s3_a_ordered_sba_0_1_0
pub const SEMANTIC_CONTRACT_CATALOG_MAGIC_S3_A_ORDERED_SBA_0_1_0_RULES_CONTRACT_HEX: &str =
    "9f4e3985e9107f52f20d0f2198f8e59e8ec66401bdd131bc271be2632c8892ca";
pub const SEMANTIC_CONTRACT_CATALOG_MAGIC_S3_A_ORDERED_SBA_0_1_0_SEMANTIC_CONTRACT_HEX: &str =
    "51efc0307d9ef8fc4fca46f8ea6e4ea5d5293cb8301c2a7917a590982079020e";

pub fn magic_s3_a_ordered_sba_0_1_0_rules_manifest() -> mtgml_model::RulesContractManifestV1 {
    mtgml_model::RulesContractManifestV1 {
        rules_authority: mtgml_model::RulesAuthorityV1::ComprehensiveRules {
            snapshot_id: "wotc-cr-2026-08-07-txt-20260819-sha256-4381ad1b39ab2c05f7d03633a20f711ed37277074d3266dcba5f38cbb527423f".to_owned(),
        },
        capability_closure: Some(vec![
            mtgml_model::CapabilityRequirementV1 {
                key: "rules/state-based-actions-combat".to_owned(),
                version: "0.1.0".to_owned(),
            },
            mtgml_model::CapabilityRequirementV1 {
                key: "rules/turn-structure".to_owned(),
                version: "0.1.0".to_owned(),
            },
            mtgml_model::CapabilityRequirementV1 {
                key: "rules/zone-incarnation".to_owned(),
                version: "0.1.0".to_owned(),
            },
        ]),
    }
}

pub fn magic_s3_a_ordered_sba_0_1_0_semantic_manifest() -> mtgml_model::SemanticContractManifestV1 {
    mtgml_model::SemanticContractManifestV1 {
        rules_contract_id: magic_s3_a_ordered_sba_0_1_0_rules_contract_id(),
        format_contract_id: None,
        content_contract_id: None,
    }
}

pub fn magic_s3_a_ordered_sba_0_1_0_rules_contract_id() -> RulesContractIdV1 {
    RulesContractIdV1::parse(
        SEMANTIC_CONTRACT_CATALOG_MAGIC_S3_A_ORDERED_SBA_0_1_0_RULES_CONTRACT_HEX,
    )
    .expect("generated canonical hex")
}

pub fn magic_s3_a_ordered_sba_0_1_0_semantic_contract_id() -> SemanticContractIdV1 {
    SemanticContractIdV1::parse(
        SEMANTIC_CONTRACT_CATALOG_MAGIC_S3_A_ORDERED_SBA_0_1_0_SEMANTIC_CONTRACT_HEX,
    )
    .expect("generated canonical hex")
}

// magic_s3_b_basic_priority_0_1_0
pub const SEMANTIC_CONTRACT_CATALOG_MAGIC_S3_B_BASIC_PRIORITY_0_1_0_RULES_CONTRACT_HEX: &str =
    "873fe066abbb7b74b68d2eb16e2ba19ef488c70dfe2014f484db28f1be1a5804";
pub const SEMANTIC_CONTRACT_CATALOG_MAGIC_S3_B_BASIC_PRIORITY_0_1_0_SEMANTIC_CONTRACT_HEX: &str =
    "c480cbae69bf0496aff83bb973a859721bfa0f969351b33b3f0b09ee3f7c5498";

pub fn magic_s3_b_basic_priority_0_1_0_rules_manifest() -> mtgml_model::RulesContractManifestV1 {
    mtgml_model::RulesContractManifestV1 {
        rules_authority: mtgml_model::RulesAuthorityV1::ComprehensiveRules {
            snapshot_id: "wotc-cr-2026-08-07-txt-20260819-sha256-4381ad1b39ab2c05f7d03633a20f711ed37277074d3266dcba5f38cbb527423f".to_owned(),
        },
        capability_closure: Some(vec![
            mtgml_model::CapabilityRequirementV1 {
                key: "rules/basic-priority".to_owned(),
                version: "0.1.0".to_owned(),
            },
            mtgml_model::CapabilityRequirementV1 {
                key: "rules/state-based-actions-combat".to_owned(),
                version: "0.1.0".to_owned(),
            },
            mtgml_model::CapabilityRequirementV1 {
                key: "rules/turn-structure".to_owned(),
                version: "0.1.0".to_owned(),
            },
            mtgml_model::CapabilityRequirementV1 {
                key: "rules/zone-incarnation".to_owned(),
                version: "0.1.0".to_owned(),
            },
        ]),
    }
}

pub fn magic_s3_b_basic_priority_0_1_0_semantic_manifest() -> mtgml_model::SemanticContractManifestV1
{
    mtgml_model::SemanticContractManifestV1 {
        rules_contract_id: magic_s3_b_basic_priority_0_1_0_rules_contract_id(),
        format_contract_id: None,
        content_contract_id: None,
    }
}

pub fn magic_s3_b_basic_priority_0_1_0_rules_contract_id() -> RulesContractIdV1 {
    RulesContractIdV1::parse(
        SEMANTIC_CONTRACT_CATALOG_MAGIC_S3_B_BASIC_PRIORITY_0_1_0_RULES_CONTRACT_HEX,
    )
    .expect("generated canonical hex")
}

pub fn magic_s3_b_basic_priority_0_1_0_semantic_contract_id() -> SemanticContractIdV1 {
    SemanticContractIdV1::parse(
        SEMANTIC_CONTRACT_CATALOG_MAGIC_S3_B_BASIC_PRIORITY_0_1_0_SEMANTIC_CONTRACT_HEX,
    )
    .expect("generated canonical hex")
}

// magic_s3_c_draw_interaction_0_1_0
pub const SEMANTIC_CONTRACT_CATALOG_MAGIC_S3_C_DRAW_INTERACTION_0_1_0_RULES_CONTRACT_HEX: &str =
    "081464ecd909d561d482b760333a68c3f3ac40de1a1532ff974cd71475115b20";
pub const SEMANTIC_CONTRACT_CATALOG_MAGIC_S3_C_DRAW_INTERACTION_0_1_0_SEMANTIC_CONTRACT_HEX: &str =
    "2818c779c0a1f3b534d5551d9842a26e64ea93fa5906e8d43b499c4a3e042cb5";

pub fn magic_s3_c_draw_interaction_0_1_0_rules_manifest() -> mtgml_model::RulesContractManifestV1 {
    mtgml_model::RulesContractManifestV1 {
        rules_authority: mtgml_model::RulesAuthorityV1::ComprehensiveRules {
            snapshot_id: "wotc-cr-2026-08-07-txt-20260819-sha256-4381ad1b39ab2c05f7d03633a20f711ed37277074d3266dcba5f38cbb527423f".to_owned(),
        },
        capability_closure: Some(vec![
            mtgml_model::CapabilityRequirementV1 {
                key: "rules/basic-priority".to_owned(),
                version: "0.1.0".to_owned(),
            },
            mtgml_model::CapabilityRequirementV1 {
                key: "rules/draw-card".to_owned(),
                version: "0.1.0".to_owned(),
            },
            mtgml_model::CapabilityRequirementV1 {
                key: "rules/state-based-actions-combat".to_owned(),
                version: "0.1.0".to_owned(),
            },
            mtgml_model::CapabilityRequirementV1 {
                key: "rules/turn-structure".to_owned(),
                version: "0.1.0".to_owned(),
            },
            mtgml_model::CapabilityRequirementV1 {
                key: "rules/zone-incarnation".to_owned(),
                version: "0.1.0".to_owned(),
            },
        ]),
    }
}

pub fn magic_s3_c_draw_interaction_0_1_0_semantic_manifest(
) -> mtgml_model::SemanticContractManifestV1 {
    mtgml_model::SemanticContractManifestV1 {
        rules_contract_id: magic_s3_c_draw_interaction_0_1_0_rules_contract_id(),
        format_contract_id: None,
        content_contract_id: None,
    }
}

pub fn magic_s3_c_draw_interaction_0_1_0_rules_contract_id() -> RulesContractIdV1 {
    RulesContractIdV1::parse(
        SEMANTIC_CONTRACT_CATALOG_MAGIC_S3_C_DRAW_INTERACTION_0_1_0_RULES_CONTRACT_HEX,
    )
    .expect("generated canonical hex")
}

pub fn magic_s3_c_draw_interaction_0_1_0_semantic_contract_id() -> SemanticContractIdV1 {
    SemanticContractIdV1::parse(
        SEMANTIC_CONTRACT_CATALOG_MAGIC_S3_C_DRAW_INTERACTION_0_1_0_SEMANTIC_CONTRACT_HEX,
    )
    .expect("generated canonical hex")
}

// magic_combat_attackers_0_1_0
pub const SEMANTIC_CONTRACT_CATALOG_MAGIC_COMBAT_ATTACKERS_0_1_0_RULES_CONTRACT_HEX: &str =
    "64a4a6198363ef5f03dbdeab714b220465216f19afb387b48a0cdb453654e6f9";
pub const SEMANTIC_CONTRACT_CATALOG_MAGIC_COMBAT_ATTACKERS_0_1_0_SEMANTIC_CONTRACT_HEX: &str =
    "fb55663090b2ea6d0ab709d56a6b58ce3a21b3beca24113008bb98684f3230a7";

pub fn magic_combat_attackers_0_1_0_rules_manifest() -> mtgml_model::RulesContractManifestV1 {
    mtgml_model::RulesContractManifestV1 {
        rules_authority: mtgml_model::RulesAuthorityV1::ComprehensiveRules {
            snapshot_id: "wotc-cr-2026-08-07-txt-20260819-sha256-4381ad1b39ab2c05f7d03633a20f711ed37277074d3266dcba5f38cbb527423f".to_owned(),
        },
        capability_closure: Some(vec![
            mtgml_model::CapabilityRequirementV1 {
                key: "rules/basic-priority".to_owned(),
                version: "0.1.0".to_owned(),
            },
            mtgml_model::CapabilityRequirementV1 {
                key: "rules/combat-phase".to_owned(),
                version: "0.1.0".to_owned(),
            },
            mtgml_model::CapabilityRequirementV1 {
                key: "rules/declare-attackers".to_owned(),
                version: "0.1.0".to_owned(),
            },
            mtgml_model::CapabilityRequirementV1 {
                key: "rules/draw-card".to_owned(),
                version: "0.1.0".to_owned(),
            },
            mtgml_model::CapabilityRequirementV1 {
                key: "rules/state-based-actions-combat".to_owned(),
                version: "0.1.0".to_owned(),
            },
            mtgml_model::CapabilityRequirementV1 {
                key: "rules/turn-structure".to_owned(),
                version: "0.1.0".to_owned(),
            },
            mtgml_model::CapabilityRequirementV1 {
                key: "rules/zone-incarnation".to_owned(),
                version: "0.1.0".to_owned(),
            },
        ]),
    }
}

pub fn magic_combat_attackers_0_1_0_semantic_manifest() -> mtgml_model::SemanticContractManifestV1 {
    mtgml_model::SemanticContractManifestV1 {
        rules_contract_id: magic_combat_attackers_0_1_0_rules_contract_id(),
        format_contract_id: None,
        content_contract_id: None,
    }
}

pub fn magic_combat_attackers_0_1_0_rules_contract_id() -> RulesContractIdV1 {
    RulesContractIdV1::parse(
        SEMANTIC_CONTRACT_CATALOG_MAGIC_COMBAT_ATTACKERS_0_1_0_RULES_CONTRACT_HEX,
    )
    .expect("generated canonical hex")
}

pub fn magic_combat_attackers_0_1_0_semantic_contract_id() -> SemanticContractIdV1 {
    SemanticContractIdV1::parse(
        SEMANTIC_CONTRACT_CATALOG_MAGIC_COMBAT_ATTACKERS_0_1_0_SEMANTIC_CONTRACT_HEX,
    )
    .expect("generated canonical hex")
}
