// @generated by scripts/generate_semantic_contract_catalog.py; DO NOT EDIT.
// Source: contracts/catalog/semantic-contracts.v1.json
//
// Manifest constants AND derived ID values for the runtime semantic
// catalog (spec §10). Rust const-evaluation cannot allocate, so the
// derived ID VALUES are checked in as canonical hex string constants
// and materialized deterministically through parse() accessors (no
// lazy statics — spec §10 bans hidden process state). The recompute KAT
// (semantic_catalog_kat.rs) re-derives every ID from these constants
// via the §9 persistence functions and fails the build on drift.
// Hand-editing any constant is a gate violation.
#![allow(dead_code)] // consumed by the KAT now and the Task-8 runtime later

use mtgml_model::{RulesContractIdV1, SemanticContractIdV1};

// synthetic_legacy_default
pub const SEMANTIC_CONTRACT_CATALOG_SYNTHETIC_LEGACY_DEFAULT_RULES_CONTRACT_HEX: &str =
    "19bac684b74115b4fab823dfae2d3e75c23ee24f78effe51e9f72a33d4a58521";
pub const SEMANTIC_CONTRACT_CATALOG_SYNTHETIC_LEGACY_DEFAULT_SEMANTIC_CONTRACT_HEX: &str =
    "66ccac959475370e641e853473cbdd7f88489399587794b43f66cfa0342b1be4";

pub fn synthetic_legacy_default_rules_manifest() -> mtgml_model::RulesContractManifestV1 {
    mtgml_model::RulesContractManifestV1 {
        rules_authority: mtgml_model::RulesAuthorityV1::SyntheticLegacy,
        capability_closure: None,
    }
}

pub fn synthetic_legacy_default_semantic_manifest() -> mtgml_model::SemanticContractManifestV1 {
    mtgml_model::SemanticContractManifestV1 {
        rules_contract_id: synthetic_legacy_default_rules_contract_id(),
        format_contract_id: None,
        content_contract_id: None,
    }
}

pub fn synthetic_legacy_default_rules_contract_id() -> RulesContractIdV1 {
    RulesContractIdV1::parse(SEMANTIC_CONTRACT_CATALOG_SYNTHETIC_LEGACY_DEFAULT_RULES_CONTRACT_HEX)
        .expect("generated canonical hex")
}

pub fn synthetic_legacy_default_semantic_contract_id() -> SemanticContractIdV1 {
    SemanticContractIdV1::parse(
        SEMANTIC_CONTRACT_CATALOG_SYNTHETIC_LEGACY_DEFAULT_SEMANTIC_CONTRACT_HEX,
    )
    .expect("generated canonical hex")
}
