#!/usr/bin/env python3
"""Generate mechanical cross-language contract vocabulary from one catalog."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

sys.dont_write_bytecode = True
ROOT = Path(__file__).resolve().parents[1]
CATALOG = ROOT / "contracts/catalog/contract-vocabulary.v1.json"


def load_catalog() -> dict[str, object]:
    data = json.loads(CATALOG.read_text(encoding="utf-8"))
    if data.get("schema_version") != "contract-vocabulary-catalog.v1":
        raise SystemExit("unsupported contract vocabulary catalog")
    return data


def jdump(value: object) -> str:
    return json.dumps(value, indent=2, sort_keys=True) + "\n"


def rust_enum(name: str, rows: list[list[str]], derives: str) -> str:
    variants = "\n".join(f"    {row[0]}," for row in rows)
    return (
        f"#[derive({derives})]\n"
        '#[serde(rename_all = "snake_case")]\n'
        f"pub enum {name} {{\n{variants}\n}}\n"
    )


def render_rust(c: dict[str, object]) -> str:
    terminal = c["terminal_reasons"]
    truncation = c["truncation_reasons"]
    results = c["player_results"]
    zones = c["zone_kinds"]
    errors = c["stable_wire_error_codes"]
    assert all(isinstance(v, list) for v in (terminal, truncation, results, zones, errors))
    common = "Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize"
    return (
        "// @generated by scripts/generate_contracts.py; DO NOT EDIT.\n"
        "// Source: contracts/catalog/contract-vocabulary.v1.json\n\n"
        "use serde::{Deserialize, Serialize};\n\n"
        + rust_enum("TerminalReason", terminal, common)
        + "\n"
        + rust_enum("TruncationReason", truncation, common)
        + "\n"
        + rust_enum("PlayerResult", results, common)
        + "\n"
        + rust_enum(
            "ZoneKind",
            zones,
            "Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Serialize, Deserialize",
        )
        + "\npub const STABLE_WIRE_ERROR_CODES: &[&str] = &[\n"
        + "".join(f"    {value!r},\n".replace("'", '"') for value in errors)
        + "];\n"
    )


def python_enum(name: str, rows: list[list[str]]) -> str:
    variants = "\n".join(f'    {row[1]} = "{row[2]}"' for row in rows)
    return f"class {name}(StrEnum):\n{variants}\n\n\n"


def render_python_frozenset(varname: str, values: list[str]) -> str:
    items = ",\n        ".join(f'"{v}"' for v in values)
    return f"{varname} = frozenset(\n    (\n        {items},\n    )\n)\n"


def render_python(c: dict[str, object]) -> str:
    terminal = c["terminal_reasons"]
    truncation = c["truncation_reasons"]
    results = c["player_results"]
    zones = c["zone_kinds"]
    events = c["observed_event_kinds"]
    errors = c["stable_wire_error_codes"]
    schema_ids = c["schema_ids"]
    assert all(isinstance(v, list) for v in (terminal, truncation, results, zones, events, errors))
    assert isinstance(schema_ids, dict)
    zone_values = [row[2] for row in zones]
    event_values = [value for value in events]
    error_values = [value for value in errors]
    return (
        "# @generated by scripts/generate_contracts.py; DO NOT EDIT.\n"
        "# Source: contracts/catalog/contract-vocabulary.v1.json\n"
        "from __future__ import annotations\n\n"
        "from enum import StrEnum\n\n\n"
        + python_enum("TerminalReason", terminal)
        + python_enum("TruncationReason", truncation)
        + python_enum("PlayerResult", results)
        + render_python_frozenset("ZONE_KINDS", zone_values)
        + "\n"
        + render_python_frozenset("OBSERVED_EVENT_KINDS", event_values)
        + "\n"
        + render_python_frozenset("STABLE_WIRE_ERROR_CODES", error_values)
        + "\n"
        + f'EPISODE_STATUS_SCHEMA = "{schema_ids["episode_status"]}"\n'
        + f'OBSERVED_EVENT_SCHEMA = "{schema_ids["observed_event"]}"\n'
    )


def episode_schema(c: dict[str, object]) -> dict[str, object]:
    terminal = [row[2] for row in c["terminal_reasons"]]
    truncated = [row[2] for row in c["truncation_reasons"]]
    results = [row[2] for row in c["player_results"]]
    player = {
        "additionalProperties": False,
        "properties": {
            "player": {"pattern": "^(0|[1-9][0-9]*)$", "type": "string"},
            "result": {"enum": results},
        },
        "required": ["player", "result"],
        "type": "object",
    }
    return {
        "$id": "episode-status.v1.schema.json",
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "oneOf": [
            {
                "additionalProperties": False,
                "properties": {"kind": {"const": "running"}},
                "required": ["kind"],
                "type": "object",
            },
            {
                "additionalProperties": False,
                "properties": {
                    "kind": {"const": "terminal"},
                    "players": {"items": player, "type": "array"},
                    "reason": {"enum": terminal},
                },
                "required": ["kind", "reason", "players"],
                "type": "object",
            },
            {
                "additionalProperties": False,
                "properties": {
                    "kind": {"const": "truncated"},
                    "players": {"items": player, "type": "array"},
                    "reason": {"enum": truncated},
                },
                "required": ["kind", "reason", "players"],
                "type": "object",
            },
        ],
        "title": "EpisodeStatus v1",
    }


def observed_schema(c: dict[str, object]) -> dict[str, object]:
    zones = [row[2] for row in c["zone_kinds"]]
    u64s = {"pattern": "^(0|[1-9][0-9]*)$", "type": "string"}
    i64 = {
        "maximum": 9223372036854775807,
        "minimum": -9223372036854775808,
        "type": "integer",
    }
    variants = [
        {
            "additionalProperties": False,
            "properties": {
                "from": {"enum": zones},
                "kind": {"const": "object_moved"},
                "new_object": u64s,
                "old_object": u64s,
                "to": {"enum": zones},
            },
            "required": ["kind", "from", "to"],
            "type": "object",
        },
        {
            "additionalProperties": False,
            "properties": {
                "kind": {"const": "object_ceased_to_exist"},
                "object": u64s,
            },
            "required": ["kind", "object"],
            "type": "object",
        },
        {
            "additionalProperties": False,
            "properties": {
                "from": i64,
                "kind": {"const": "life_changed"},
                "player": u64s,
                "to": i64,
            },
            "required": ["kind", "player", "from", "to"],
            "type": "object",
        },
        {
            "additionalProperties": False,
            "properties": {
                "kind": {"const": "object_tapped"},
                "object": u64s,
                "tapped": {"type": "boolean"},
            },
            "required": ["kind", "object", "tapped"],
            "type": "object",
        },
        {
            "additionalProperties": False,
            "properties": {
                "actor": u64s,
                "kind": {"const": "decision_available"},
            },
            "required": ["kind", "actor"],
            "type": "object",
        },
        {
            "additionalProperties": False,
            "properties": {
                "exclusive_upper_bound": {
                    "maximum": 18446744073709551615,
                    "minimum": 1,
                    "type": "integer",
                },
                "kind": {"const": "random_outcome_visible"},
                "label": {"minLength": 1, "type": "string"},
                "value": {
                    "maximum": 18446744073709551615,
                    "minimum": 0,
                    "type": "integer",
                },
            },
            "required": ["kind", "label", "exclusive_upper_bound", "value"],
            "type": "object",
        },
        {
            "additionalProperties": False,
            "properties": {
                "code": {"minLength": 1, "type": "string"},
                "kind": {"const": "public_outcome"},
            },
            "required": ["kind", "code"],
            "type": "object",
        },
    ]
    expected = c["observed_event_kinds"]
    actual = [item["properties"]["kind"]["const"] for item in variants]
    if actual != expected:
        raise SystemExit(f"observed-event catalog/template drift: {actual!r} != {expected!r}")
    return {
        "$id": "observed-event-envelope.v1.schema.json",
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "additionalProperties": False,
        "properties": {
            "event": {"oneOf": variants},
            "schema_version": {"const": "observed-event-envelope.v1"},
            "sequence": u64s,
            "state_revision": u64s,
        },
        "required": ["schema_version", "sequence", "state_revision", "event"],
        "title": "ObservedEventEnvelope v1",
        "type": "object",
    }


def render_docs(c: dict[str, object]) -> str:
    def values(key: str) -> str:
        return ", ".join(f"`{row[2]}`" for row in c[key])

    events = ", ".join(f"`{value}`" for value in c["observed_event_kinds"])
    errors = "\n".join(f"- `{value}`" for value in c["stable_wire_error_codes"])
    return (
        "# Generated Contract Vocabulary\n\n"
        "> Generated by `scripts/generate_contracts.py` from "
        "`contracts/catalog/contract-vocabulary.v1.json`. Do not edit directly.\n\n"
        "The catalog owns only mechanically duplicated public vocabulary. It does **not** "
        "own Magic semantics, DTO structure, information-flow rules, cross-field validation, "
        "or state invariants.\n\n"
        f"## Episode terminal reasons\n\n{values('terminal_reasons')}\n\n"
        f"## Episode truncation reasons\n\n{values('truncation_reasons')}\n\n"
        f"## Player results\n\n{values('player_results')}\n\n"
        f"## Zone kinds\n\n{values('zone_kinds')}\n\n"
        f"## Observed-event kinds\n\n{events}\n\n"
        f"## Stable wire error codes owned by this catalog\n\n{errors}\n"
    )


def rendered() -> dict[str, str]:
    catalog = load_catalog()
    return {
        "crates/mtgml-model/src/generated_contract_vocab.rs": render_rust(catalog),
        "python/src/mtgml/_generated_contract_vocab.py": render_python(catalog),
        "schemas/episode-status.v1.schema.json": jdump(episode_schema(catalog)),
        "schemas/observed-event-envelope.v1.schema.json": jdump(observed_schema(catalog)),
        "docs/generated/CONTRACT_VOCABULARY.md": render_docs(catalog),
    }


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    drift: list[str] = []
    for rel, content in rendered().items():
        target = ROOT / rel
        if args.check:
            if not target.is_file() or target.read_text(encoding="utf-8") != content:
                drift.append(rel)
        else:
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(content, encoding="utf-8")
    if drift:
        print("generated contract drift:")
        for rel in drift:
            print(f"  - {rel}")
        return 1
    print(f"PASS: contract vocabulary {'matches' if args.check else 'generated from'} catalog")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
