#!/usr/bin/env python3
"""Generate semantic-contract catalog constants and V6 execution profiles (spec §10).

Single generator for the single hand-authored manifest source
``contracts/catalog/semantic-contracts.v1.json``. Emits BOTH the Rust manifest
constants AND the derived ``RulesContractIdV1``/``SemanticContractIdV1``
values into ``crates/mtgml-environment/src/semantic_catalog_generated.rs``.

Also emits the runtime execution-profile mapping for ``crates/mtgml-rules``
into ``crates/mtgml-rules/src/semantic_execution_generated.rs``.

Layering (review Fix-02):

- ``render_catalog_generated`` is a pure renderer of VALID manifest facts.
  It derives IDs exclusively via the Task-2 Python mechanical mirrors (no
  digest logic of its own) and can render any manifest the §7 contract
  accepts.
- ``render_rules_execution_generated`` derives the Magic execution
  authority mapping from the SAME source manifest. It identifies the
    exact ComprehensiveRules contracts authorized for
    ``ExecutionProgramV1::MagicRules`` by the current V6 runtime.
- ``assert_production_policy`` is the PRODUCTION source validator.
- The CLI (``main``) always enforces the production policy before rendering
  and checks BOTH targets byte-exactly on ``--check``.

Generated-file policy (Batch G FND-030): output is written as exact UTF-8/LF
bytes so byte comparison is host-independent.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

# The project Python root is added so the Task-2 mirrors can be imported from
# a bare checkout without requiring an editable install.
sys.path.insert(0, str(ROOT / "python" / "src"))

SOURCE_REL = "contracts/catalog/semantic-contracts.v1.json"
SOURCE_PATH = ROOT / SOURCE_REL
TARGET_REL = "crates/mtgml-environment/src/semantic_catalog_generated.rs"
TARGET_PATH = ROOT / TARGET_REL

RULES_TARGET_REL = "crates/mtgml-rules/src/semantic_execution_generated.rs"
RULES_TARGET_PATH = ROOT / RULES_TARGET_REL

RULES_ENTRY_ID = "magic_turn_structure_0_1_0"
S3A_ENTRY_ID = "magic_s3_a_ordered_sba_0_1_0"
S3B_ENTRY_ID = "magic_s3_b_basic_priority_0_1_0"
S3C_ENTRY_ID = "magic_s3_c_draw_interaction_0_1_0"
COMBAT_ENTRY_ID = "magic_combat_attackers_0_1_0"


def render_rules_execution_generated(
    catalog: dict[str, object] | None = None,
) -> str:
    """Render exact S1, S3.A, S3.B, S3.C, and combat Magic profiles."""
    catalog = catalog if catalog is not None else load_source()
    entries = {
        entry.get("entry_id"): entry for entry in catalog["entries"] if isinstance(entry, dict)
    }
    turn_structure_entry = entries.get(RULES_ENTRY_ID)
    ordered_sba_entry = entries.get(S3A_ENTRY_ID)
    basic_priority_entry = entries.get(S3B_ENTRY_ID)
    draw_entry = entries.get(S3C_ENTRY_ID)
    combat_entry = entries.get(COMBAT_ENTRY_ID)
    synthetic = entries.get("synthetic_legacy_default")
    if (
        turn_structure_entry is None
        or ordered_sba_entry is None
        or basic_priority_entry is None
        or draw_entry is None
        or combat_entry is None
        or synthetic is None
    ):
        raise SystemExit("production catalog is missing a required execution identity")
    for entry in (
        turn_structure_entry,
        ordered_sba_entry,
        basic_priority_entry,
        draw_entry,
        combat_entry,
        synthetic,
    ):
        validate_entry_facts(entry)
    _, s1_semantic = derive_ids(turn_structure_entry)
    _, s3a_semantic = derive_ids(ordered_sba_entry)
    _, s3b_semantic = derive_ids(basic_priority_entry)
    _, s3c_semantic = derive_ids(draw_entry)
    _, combat_semantic = derive_ids(combat_entry)
    _, synthetic_semantic = derive_ids(synthetic)

    def has_capability(entry: dict[str, object], key: str) -> bool:
        closure = entry.get("capability_closure") or []
        return any(
            isinstance(capability, dict)
            and capability.get("key") == key
            and capability.get("version") == "0.1.0"
            for capability in closure
        )

    template = r"""// @generated by scripts/generate_semantic_contract_catalog.py; DO NOT EDIT.
// Source: contracts/catalog/semantic-contracts.v1.json
// Exact production Magic execution profiles derived from the semantic catalog.

use mtgml_model::{ExecutionProgramV1, SemanticContractIdV1};

pub(crate) const MAGIC_TURN_STRUCTURE_SEMANTIC_CONTRACT_HEX: &str =
    "@S1_ID@";
pub(crate) const MAGIC_S3_A_SEMANTIC_CONTRACT_HEX: &str =
    "@S3_ID@";
pub(crate) const MAGIC_S3_B_SEMANTIC_CONTRACT_HEX: &str =
    "@S3B_ID@";
pub(crate) const MAGIC_S3_C_SEMANTIC_CONTRACT_HEX: &str =
    "@S3C_ID@";
pub(crate) const MAGIC_COMBAT_ATTACKERS_SEMANTIC_CONTRACT_HEX: &str =
    "@COMBAT_ID@";
pub(crate) const SYNTHETIC_LEGACY_SEMANTIC_CONTRACT_HEX: &str =
    "@SYNTHETIC_ID@";

pub(crate) fn magic_turn_structure_0_1_0_semantic_contract_id() -> SemanticContractIdV1 {
    SemanticContractIdV1::parse(MAGIC_TURN_STRUCTURE_SEMANTIC_CONTRACT_HEX)
        .expect("generated canonical hex")
}
pub(crate) fn magic_s3_a_ordered_sba_0_1_0_semantic_contract_id() -> SemanticContractIdV1 {
    SemanticContractIdV1::parse(MAGIC_S3_A_SEMANTIC_CONTRACT_HEX).expect("generated canonical hex")
}
pub(crate) fn magic_s3_b_basic_priority_0_1_0_semantic_contract_id() -> SemanticContractIdV1 {
    SemanticContractIdV1::parse(MAGIC_S3_B_SEMANTIC_CONTRACT_HEX).expect("generated canonical hex")
}
pub(crate) fn magic_s3_c_draw_interaction_0_1_0_semantic_contract_id() -> SemanticContractIdV1 {
    SemanticContractIdV1::parse(MAGIC_S3_C_SEMANTIC_CONTRACT_HEX).expect("generated canonical hex")
}
pub(crate) fn magic_combat_attackers_0_1_0_semantic_contract_id() -> SemanticContractIdV1 {
    SemanticContractIdV1::parse(MAGIC_COMBAT_ATTACKERS_SEMANTIC_CONTRACT_HEX)
        .expect("generated canonical hex")
}
pub(crate) fn synthetic_legacy_default_semantic_contract_id() -> SemanticContractIdV1 {
    SemanticContractIdV1::parse(SYNTHETIC_LEGACY_SEMANTIC_CONTRACT_HEX)
        .expect("generated canonical hex")
}

pub(crate) struct MagicExecutionProfile {
    turn_structure_0_1_0: bool,
    state_based_actions_combat_0_1_0: bool,
    basic_priority_0_1_0: bool,
    draw_card_0_1_0: bool,
    combat_phase_0_1_0: bool,
    declare_attackers_0_1_0: bool,
}
impl MagicExecutionProfile {
    pub(crate) fn allows_turn_structure_0_1_0(&self) -> bool {
        self.turn_structure_0_1_0
    }
    pub(crate) fn allows_state_based_actions_combat_0_1_0(&self) -> bool {
        self.state_based_actions_combat_0_1_0
    }
    pub(crate) fn allows_basic_priority_0_1_0(&self) -> bool {
        self.basic_priority_0_1_0
    }
    pub(crate) fn allows_draw_card_0_1_0(&self) -> bool {
        self.draw_card_0_1_0
    }
    pub(crate) fn allows_combat_attackers_0_1_0(&self) -> bool {
        self.combat_phase_0_1_0 && self.declare_attackers_0_1_0
    }
    pub(crate) fn is_turn_structure_only_profile(&self) -> bool {
        self.allows_turn_structure_0_1_0()
            && !self.allows_state_based_actions_combat_0_1_0()
            && !self.allows_basic_priority_0_1_0()
            && !self.allows_draw_card_0_1_0()
            && !self.allows_combat_attackers_0_1_0()
    }
}
#[cfg(test)]
pub(crate) fn test_only_magic_execution_profile(
    admitted_contract: SemanticContractIdV1,
    turn_structure_0_1_0: bool,
) -> MagicExecutionProfile {
    MagicExecutionProfile {
        turn_structure_0_1_0: turn_structure_0_1_0
            && admitted_contract == magic_turn_structure_0_1_0_semantic_contract_id(),
        state_based_actions_combat_0_1_0: false,
        basic_priority_0_1_0: false,
        draw_card_0_1_0: false,
        combat_phase_0_1_0: false,
        declare_attackers_0_1_0: false,
    }
}
pub(crate) fn magic_execution_profile(
    semantic_contract_id: SemanticContractIdV1,
) -> Option<MagicExecutionProfile> {
    if semantic_contract_id == magic_turn_structure_0_1_0_semantic_contract_id() {
        return Some(MagicExecutionProfile {
            turn_structure_0_1_0: @TURN_STRUCTURE_TURN@,
            state_based_actions_combat_0_1_0: false,
            basic_priority_0_1_0: false,
            draw_card_0_1_0: false,
            combat_phase_0_1_0: false,
            declare_attackers_0_1_0: false,
        });
    }
    if semantic_contract_id == magic_s3_a_ordered_sba_0_1_0_semantic_contract_id() {
        return Some(MagicExecutionProfile {
            turn_structure_0_1_0: @ORDERED_SBA_TURN@,
            state_based_actions_combat_0_1_0: @ORDERED_SBA_ACTIONS@,
            basic_priority_0_1_0: false,
            draw_card_0_1_0: false,
            combat_phase_0_1_0: false,
            declare_attackers_0_1_0: false,
        });
    }
    if semantic_contract_id == magic_s3_b_basic_priority_0_1_0_semantic_contract_id() {
        return Some(MagicExecutionProfile {
            turn_structure_0_1_0: @BASIC_PRIORITY_TURN@,
            state_based_actions_combat_0_1_0: @BASIC_PRIORITY_SBA@,
            basic_priority_0_1_0: @BASIC_PRIORITY_PERMISSION@,
            draw_card_0_1_0: false,
            combat_phase_0_1_0: false,
            declare_attackers_0_1_0: false,
        });
    }
    if semantic_contract_id == magic_s3_c_draw_interaction_0_1_0_semantic_contract_id() {
        return Some(MagicExecutionProfile {
            turn_structure_0_1_0: @DRAW_TURN@,
            state_based_actions_combat_0_1_0: @DRAW_SBA@,
            basic_priority_0_1_0: @DRAW_PRIORITY@,
            draw_card_0_1_0: @DRAW_CARD_PERMISSION@,
            combat_phase_0_1_0: false,
            declare_attackers_0_1_0: false,
        });
    }
    if semantic_contract_id == magic_combat_attackers_0_1_0_semantic_contract_id() {
        return Some(MagicExecutionProfile {
            turn_structure_0_1_0: @COMBAT_TURN@,
            state_based_actions_combat_0_1_0: @COMBAT_SBA@,
            basic_priority_0_1_0: @COMBAT_PRIORITY@,
            draw_card_0_1_0: @COMBAT_DRAW@,
            combat_phase_0_1_0: @COMBAT_PHASE@,
            declare_attackers_0_1_0: @DECLARE_ATTACKERS@,
        });
    }
    None
}
pub fn execution_contract_supported(
    program: ExecutionProgramV1,
    semantic_contract_id: &SemanticContractIdV1,
) -> bool {
    match program {
        ExecutionProgramV1::SyntheticRulesCompat => {
            *semantic_contract_id == synthetic_legacy_default_semantic_contract_id()
        }
        ExecutionProgramV1::MagicRules => {
            magic_execution_profile(semantic_contract_id.clone()).is_some()
        }
    }
}
"""
    return (
        template.replace("@S1_ID@", s1_semantic)
        .replace("@S3_ID@", s3a_semantic)
        .replace("@S3B_ID@", s3b_semantic)
        .replace("@S3C_ID@", s3c_semantic)
        .replace("@COMBAT_ID@", combat_semantic)
        .replace("@COMBAT_TURN@", str(has_capability(combat_entry, "rules/turn-structure")).lower())
        .replace("@COMBAT_SBA@", str(has_capability(combat_entry, "rules/state-based-actions-combat")).lower())
        .replace("@COMBAT_PRIORITY@", str(has_capability(combat_entry, "rules/basic-priority")).lower())
        .replace("@COMBAT_DRAW@", str(has_capability(combat_entry, "rules/draw-card")).lower())
        .replace("@COMBAT_PHASE@", str(has_capability(combat_entry, "rules/combat-phase")).lower())
        .replace("@DECLARE_ATTACKERS@", str(has_capability(combat_entry, "rules/declare-attackers")).lower())
        .replace("@SYNTHETIC_ID@", synthetic_semantic)
        .replace(
            "@TURN_STRUCTURE_TURN@",
            str(has_capability(turn_structure_entry, "rules/turn-structure")).lower(),
        )
        .replace(
            "@ORDERED_SBA_TURN@",
            str(has_capability(ordered_sba_entry, "rules/turn-structure")).lower(),
        )
        .replace(
            "@ORDERED_SBA_ACTIONS@",
            str(has_capability(ordered_sba_entry, "rules/state-based-actions-combat")).lower(),
        )
        .replace(
            "@BASIC_PRIORITY_TURN@",
            str(has_capability(basic_priority_entry, "rules/turn-structure")).lower(),
        )
        .replace(
            "@BASIC_PRIORITY_SBA@",
            str(has_capability(basic_priority_entry, "rules/state-based-actions-combat")).lower(),
        )
        .replace(
            "@BASIC_PRIORITY_PERMISSION@",
            str(has_capability(basic_priority_entry, "rules/basic-priority")).lower(),
        )
        .replace("@DRAW_TURN@", str(has_capability(draw_entry, "rules/turn-structure")).lower())
        .replace(
            "@DRAW_SBA@",
            str(has_capability(draw_entry, "rules/state-based-actions-combat")).lower(),
        )
        .replace("@DRAW_PRIORITY@", str(has_capability(draw_entry, "rules/basic-priority")).lower())
        .replace(
            "@DRAW_CARD_PERMISSION@", str(has_capability(draw_entry, "rules/draw-card")).lower()
        )
    )


FACT_KEYS = {
    "entry_id",
    "rules_authority",
    "capability_closure",
    "format_contract_id",
    "content_contract_id",
}


def load_source(path: Path | None = None) -> dict[str, object]:
    source = path if path is not None else SOURCE_PATH
    data = json.loads(source.read_text(encoding="utf-8"))
    if data.get("schema_version") != "semantic-contracts-catalog.v1":
        raise SystemExit("unsupported semantic-contracts catalog")
    entries = data.get("entries")
    if not isinstance(entries, list) or not entries:
        raise SystemExit("semantic-contracts catalog must contain entries")
    return data


def validate_entry_facts(entry: dict[str, object]) -> None:
    """The source carries manifest FACTS only; derived identity is generated
    output and must never appear in the hand-authored source (no second
    authority for identity)."""
    if set(entry) != FACT_KEYS:
        raise SystemExit(
            f"catalog entry keys must be exactly {sorted(FACT_KEYS)}; got {sorted(entry)}"
        )


def rust_string_literal(value: object, label: str) -> str:
    """Render a plain double-quoted Rust string literal, fail-closed for any
    character this generator does not represent."""
    if (
        not isinstance(value, str)
        or not value
        or not value.isascii()
        or '"' in value
        or "\\" in value
    ):
        raise SystemExit(f"{label} is not representable as a plain Rust string literal")
    return f'"{value}"'


def derive_ids(entry: dict[str, object]) -> tuple[str, str]:
    """Derive both IDs via the Task-2 Python mechanical mirrors — the ONLY
    digest path; this generator contains no digest logic of its own. Invalid
    manifest facts fail closed here, before any emission."""
    from mtgml.persistence import (
        calculate_rules_contract_id_v1,
        calculate_semantic_contract_id_v1,
    )

    rules_id = calculate_rules_contract_id_v1(
        {
            "rules_authority": entry["rules_authority"],
            "capability_closure": entry["capability_closure"],
        }
    )
    semantic_id = calculate_semantic_contract_id_v1(
        {
            "rules_contract_id": rules_id,
            "format_contract_id": entry["format_contract_id"],
            "content_contract_id": entry["content_contract_id"],
        }
    )
    return rules_id, semantic_id


def render_rules_authority(authority: object) -> list[str]:
    if not isinstance(authority, dict):
        raise SystemExit("rules_authority must be an object")
    variant = authority.get("variant")
    if variant == "synthetic_legacy":
        if set(authority) != {"variant"}:
            raise SystemExit("synthetic_legacy authority carries no payload fields")
        return ["        rules_authority: mtgml_model::RulesAuthorityV1::SyntheticLegacy,"]
    if variant == "comprehensive_rules":
        if set(authority) != {"variant", "snapshot_id"}:
            raise SystemExit("comprehensive_rules authority carries exactly a snapshot_id")
        snapshot = rust_string_literal(authority["snapshot_id"], "comprehensive snapshot_id")
        return [
            "        rules_authority: mtgml_model::RulesAuthorityV1::ComprehensiveRules {",
            f"            snapshot_id: {snapshot}.to_owned(),",
            "        },",
        ]
    raise SystemExit(f"unknown rules authority variant: {variant!r}")


def render_closure(closure: object) -> list[str]:
    if closure is None:
        return ["        capability_closure: None,"]
    if not isinstance(closure, list) or not closure:
        raise SystemExit("capability_closure must be null or a non-empty list")
    lines = ["        capability_closure: Some(vec!["]
    for item in closure:
        if not isinstance(item, dict) or set(item) != {"key", "version"}:
            raise SystemExit("capability entry must carry exactly key and version")
        key = rust_string_literal(item["key"], "capability key")
        version = rust_string_literal(item["version"], "capability version")
        lines.append("            mtgml_model::CapabilityRequirementV1 {")
        lines.append(f"                key: {key}.to_owned(),")
        lines.append(f"                version: {version}.to_owned(),")
        lines.append("            },")
    lines.append("        ]),")
    return lines


def parse_call_lines(type_name: str, const_name: str) -> list[str]:
    """Emit a rustfmt-canonical ``Type::parse(CONST)`` expression.

    rustfmt (max_width 100) keeps the call on one line when it fits and
    otherwise breaks the argument with a trailing comma and re-indents the
    following ``.expect``. The generator reproduces both forms exactly so the
    emitted file survives ``cargo fmt --check`` byte-identically.
    """
    single = f"    {type_name}::parse({const_name})"
    if len(single) <= 100:
        return [single, '        .expect("generated canonical hex")']
    return [
        f"    {type_name}::parse(",
        f"        {const_name},",
        "    )",
        '    .expect("generated canonical hex")',
    ]


def render_catalog_generated(catalog: dict[str, object] | None = None) -> str:
    catalog = catalog if catalog is not None else load_source()
    lines: list[str] = []
    lines.append("// @generated by scripts/generate_semantic_contract_catalog.py; DO NOT EDIT.")
    lines.append(f"// Source: {SOURCE_REL}")
    lines.append("//")
    lines.append("// Manifest constants AND derived ID values for the runtime semantic")
    lines.append("// catalog (spec §10). Rust const-evaluation cannot allocate, so the")
    lines.append("// derived ID VALUES are checked in as canonical hex string constants")
    lines.append("// and materialized deterministically through parse() accessors (no")
    lines.append("// lazy statics — spec §10 bans hidden process state). The recompute KAT")
    lines.append("// (semantic_catalog_kat.rs) re-derives every ID from these generated")
    lines.append("// manifest constants via the §9 persistence functions and fails the")
    lines.append("// build on drift. Hand-editing any constant is a gate violation.")
    lines.append(
        "#![allow(dead_code)] // hex constants and *_rules_contract_id accessors are KAT/test-only"
    )
    lines.append("")
    lines.append("use mtgml_model::{RulesContractIdV1, SemanticContractIdV1};")
    lines.append("")
    for entry in catalog["entries"]:
        if not isinstance(entry, dict):
            raise SystemExit("catalog entry must be an object")
        validate_entry_facts(entry)
        entry_id = entry["entry_id"]
        if not isinstance(entry_id, str) or not entry_id:
            raise SystemExit("catalog entry_id must be a non-empty string")
        if entry_id != entry_id.replace("-", "_"):
            raise SystemExit("catalog entry_id must not contain hyphens")
        if entry["format_contract_id"] is not None or entry["content_contract_id"] is not None:
            raise SystemExit(
                f"catalog entry {entry_id!r}: format/content dimensions must be null "
                "in the V5 slice"
            )
        rules_id, semantic_id = derive_ids(entry)
        snake = entry_id.replace("-", "_")
        const_prefix = f"SEMANTIC_CONTRACT_CATALOG_{snake.upper()}"
        lines.append(f"// {entry_id}")
        lines.append(f"pub const {const_prefix}_RULES_CONTRACT_HEX: &str =")
        lines.append(f'    "{rules_id}";')
        lines.append(f"pub const {const_prefix}_SEMANTIC_CONTRACT_HEX: &str =")
        lines.append(f'    "{semantic_id}";')
        lines.append("")
        # GENERATED MANIFEST FACTS: the manifest constructors are emitted from
        # the source facts themselves, so the recompute KAT builds its
        # manifests exclusively from GENERATED data — no hand-copied manifest
        # anywhere (single-source-of-truth chain, spec §10).
        lines.append(f"pub fn {snake}_rules_manifest() -> mtgml_model::RulesContractManifestV1 {{")
        lines.append("    mtgml_model::RulesContractManifestV1 {")
        lines.extend(render_rules_authority(entry["rules_authority"]))
        lines.extend(render_closure(entry["capability_closure"]))
        lines.append("    }")
        lines.append("}")
        lines.append("")
        semantic_manifest_signature = f"pub fn {snake}_semantic_manifest"
        semantic_manifest_return = "mtgml_model::SemanticContractManifestV1"
        semantic_manifest_head = f"{semantic_manifest_signature}() -> {semantic_manifest_return}"
        if len(f"{semantic_manifest_head} {{") <= 100:
            lines.append(f"{semantic_manifest_head} {{")
        elif len(semantic_manifest_head) <= 101:
            lines.append(semantic_manifest_head)
            lines.append("{")
        else:
            lines.append(f"{semantic_manifest_signature}(")
            lines.append(f") -> {semantic_manifest_return} {{")
        lines.append("    mtgml_model::SemanticContractManifestV1 {")
        lines.append(f"        rules_contract_id: {snake}_rules_contract_id(),")
        lines.append("        format_contract_id: None,")
        lines.append("        content_contract_id: None,")
        lines.append("    }")
        lines.append("}")
        lines.append("")
        lines.append(f"pub fn {snake}_rules_contract_id() -> RulesContractIdV1 {{")
        lines.extend(
            parse_call_lines(
                "RulesContractIdV1",
                f"{const_prefix}_RULES_CONTRACT_HEX",
            )
        )
        lines.append("}")
        lines.append("")
        lines.append(f"pub fn {snake}_semantic_contract_id() -> SemanticContractIdV1 {{")
        lines.extend(
            parse_call_lines(
                "SemanticContractIdV1",
                f"{const_prefix}_SEMANTIC_CONTRACT_HEX",
            )
        )
        lines.append("}")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def assert_production_policy(catalog: dict[str, object]) -> None:
    """Require Synthetic, frozen S1, and distinct bounded S3.A/S3.B identities."""
    entries = catalog["entries"]
    if len(entries) != 6:
        raise SystemExit(
            "production semantic-contract catalog must contain exactly six entries; "
            f"got {len(entries)}"
        )
    by_id = {}
    for entry in entries:
        if not isinstance(entry, dict):
            raise SystemExit("catalog entry must be an object")
        validate_entry_facts(entry)
        entry_id = entry["entry_id"]
        if entry_id in by_id:
            raise SystemExit(f"duplicate production semantic entry {entry_id!r}")
        by_id[entry_id] = entry
    synthetic = by_id.get("synthetic_legacy_default")
    turn_structure_entry = by_id.get(RULES_ENTRY_ID)
    ordered_sba_entry = by_id.get(S3A_ENTRY_ID)
    basic_priority_entry = by_id.get(S3B_ENTRY_ID)
    draw_entry = by_id.get(S3C_ENTRY_ID)
    combat_entry = by_id.get(COMBAT_ENTRY_ID)
    if (
        synthetic is None
        or turn_structure_entry is None
        or ordered_sba_entry is None
        or basic_priority_entry is None
        or draw_entry is None
        or combat_entry is None
    ):
        raise SystemExit(
            "production semantic catalog requires Synthetic, exact S1, S3.A, S3.B, S3.C, and combat entries"
        )
    if (
        synthetic["rules_authority"] != {"variant": "synthetic_legacy"}
        or synthetic["capability_closure"] is not None
        or synthetic["format_contract_id"] is not None
        or synthetic["content_contract_id"] is not None
    ):
        raise SystemExit("synthetic production entry must retain its exact legacy identity")
    expected_authority = {
        "variant": "comprehensive_rules",
        "snapshot_id": (
            "wotc-cr-2026-08-07-txt-20260819-sha256-"
            "4381ad1b39ab2c05f7d03633a20f711ed37277074d3266dcba5f38cbb527423f"
        ),
    }
    if turn_structure_entry["rules_authority"] != expected_authority or turn_structure_entry[
        "capability_closure"
    ] != [{"key": "rules/turn-structure", "version": "0.1.0"}]:
        raise SystemExit("S1 must preserve the exact historical turn-structure-only closure")
    if ordered_sba_entry["rules_authority"] != expected_authority or ordered_sba_entry[
        "capability_closure"
    ] != [
        {"key": "rules/state-based-actions-combat", "version": "0.1.0"},
        {"key": "rules/turn-structure", "version": "0.1.0"},
        {"key": "rules/zone-incarnation", "version": "0.1.0"},
    ]:
        raise SystemExit("S3.A must use the exact reviewed turn/SBA/zone-incarnation closure")
    if basic_priority_entry["rules_authority"] != expected_authority or basic_priority_entry[
        "capability_closure"
    ] != [
        {"key": "rules/basic-priority", "version": "0.1.0"},
        {"key": "rules/state-based-actions-combat", "version": "0.1.0"},
        {"key": "rules/turn-structure", "version": "0.1.0"},
        {"key": "rules/zone-incarnation", "version": "0.1.0"},
    ]:
        raise SystemExit("S3.B must use the exact reviewed priority/SBA/turn/zone closure")
    if draw_entry["rules_authority"] != expected_authority or draw_entry["capability_closure"] != [
        {"key": "rules/basic-priority", "version": "0.1.0"},
        {"key": "rules/draw-card", "version": "0.1.0"},
        {"key": "rules/state-based-actions-combat", "version": "0.1.0"},
        {"key": "rules/turn-structure", "version": "0.1.0"},
        {"key": "rules/zone-incarnation", "version": "0.1.0"},
    ]:
        raise SystemExit("S3.C must use the exact reviewed draw/priority/SBA/turn/zone closure")
    if combat_entry["rules_authority"] != expected_authority or combat_entry["capability_closure"] != [
        {"key": "rules/basic-priority", "version": "0.1.0"},
        {"key": "rules/combat-phase", "version": "0.1.0"},
        {"key": "rules/declare-attackers", "version": "0.1.0"},
        {"key": "rules/draw-card", "version": "0.1.0"},
        {"key": "rules/state-based-actions-combat", "version": "0.1.0"},
        {"key": "rules/turn-structure", "version": "0.1.0"},
        {"key": "rules/zone-incarnation", "version": "0.1.0"},
    ]:
        raise SystemExit("combat profile must use the exact reviewed cumulative combat closure")
    for entry in (turn_structure_entry, ordered_sba_entry, basic_priority_entry, draw_entry, combat_entry):
        if entry["format_contract_id"] is not None or entry["content_contract_id"] is not None:
            raise SystemExit(
                "current S1/S3.A production identities have null format/content dimensions"
            )


def generated_bytes(content: str) -> bytes:
    return content.encode("utf-8")


def write_generated(target: Path, content: str) -> None:
    target.write_bytes(generated_bytes(content))


def generated_bytes_match(target: Path, content: str) -> bool:
    return target.is_file() and target.read_bytes() == generated_bytes(content)


def check_catalog_paths(targets: list[Path], catalog: dict[str, object] | None = None) -> int:
    """Policy-free comparison helper: renders the catalog target from the
    given catalog (or the current SOURCE_PATH) and reports drift.

    This is policy-free: it accepts any valid manifest and does NOT
    require both exact production S1 and S3.A Magic entries.
    """
    content = render_catalog_generated(catalog)
    drift = [str(target) for target in targets if not generated_bytes_match(target, content)]
    if drift:
        print("generated semantic-contract catalog drift:")
        for rel in drift:
            print(f"  - {rel}")
        return 1
    return 0


def check_rules_execution_path(target: Path, catalog: dict[str, object] | None = None) -> int:
    """Production execution-profile check: renders the rules execution
    target and reports drift. This requires the exact production S1 and S3.A
    Magic entries in the catalog.
    """
    rules_content = render_rules_execution_generated(catalog)
    if not generated_bytes_match(target, rules_content):
        print("generated rules execution drift:")
        print(f"  - {target}")
        return 1
    return 0


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    catalog = load_source()
    assert_production_policy(catalog)
    content = render_catalog_generated(catalog)
    rules_content = render_rules_execution_generated(catalog)
    if args.check:
        cat_drift = check_catalog_paths([TARGET_PATH], catalog=catalog)
        rules_drift = check_rules_execution_path(RULES_TARGET_PATH, catalog=catalog)
        if cat_drift or rules_drift:
            return 1
        print("PASS: semantic-contract catalog matches source")
        return 0
    TARGET_PATH.parent.mkdir(parents=True, exist_ok=True)
    write_generated(TARGET_PATH, content)
    RULES_TARGET_PATH.parent.mkdir(parents=True, exist_ok=True)
    write_generated(RULES_TARGET_PATH, rules_content)
    print(f"PASS: semantic-contract catalog generated to {TARGET_REL}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
