#!/usr/bin/env python3
"""Generate the V5 semantic-contract catalog constants (spec §10 chain).

Single generator for the single hand-authored manifest source
``contracts/catalog/semantic-contract*.json``. Emits BOTH the Rust manifest
constants AND the derived ``RulesContractIdV1``/``SemanticContractIdV1``
constants into ``crates/mtgml-environment/src/semantic_catalog_generated.rs``.

The generator contains NO digest logic of its own: it derives IDs via the
Task-2 Python mechanical mirrors in ``python/src/mtgml/persistence.py`` and
re-reads ONLY the machine-readable source. ``--check`` fails closed on stale
generated output; rerun is deterministic (zero diff).

Generated-file policy (Batch G FND-030): output is written as exact UTF-8/LF
bytes so byte comparison is host-independent.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

# The project Python root is added so the Task-2 mirrors can be imported from
# a bare checkout without requiring an editable install.
sys.path.insert(0, str(ROOT / "python" / "src"))

SOURCE_REL = "contracts/catalog/semantic-contracts.v1.json"
SOURCE_PATH = ROOT / SOURCE_REL
TARGET_REL = "crates/mtgml-environment/src/semantic_catalog_generated.rs"
TARGET_PATH = ROOT / TARGET_REL


def load_source() -> dict[str, object]:
    data = json.loads(SOURCE_PATH.read_text(encoding="utf-8"))
    if data.get("schema_version") != "semantic-contracts-catalog.v1":
        raise SystemExit("unsupported semantic-contracts catalog")
    entries = data.get("entries")
    if not isinstance(entries, list) or not entries:
        raise SystemExit("semantic-contracts catalog must contain entries")
    return data


def derive_ids(entry: dict[str, object]) -> tuple[str, str]:
    from mtgml.persistence import (
        calculate_rules_contract_id_v1,
        calculate_semantic_contract_id_v1,
    )

    rules_id = calculate_rules_contract_id_v1(
        {
            "rules_authority": entry["rules_authority"],
            "capability_closure": entry["capability_closure"],
        }
    )
    semantic_id = calculate_semantic_contract_id_v1(
        {
            "rules_contract_id": rules_id,
            "format_contract_id": entry["format_contract_id"],
            "content_contract_id": entry["content_contract_id"],
        }
    )
    return rules_id, semantic_id


def parse_call_lines(type_name: str, const_name: str) -> list[str]:
    """Emit a rustfmt-canonical ``Type::parse(CONST)`` expression.

    rustfmt (max_width 100) keeps the call on one line when it fits and
    otherwise breaks the argument with a trailing comma and re-indents the
    following ``.expect``. The generator reproduces both forms exactly so the
    emitted file survives ``cargo fmt --check`` byte-identically.
    """
    single = f"    {type_name}::parse({const_name})"
    if len(single) <= 100:
        return [single, "        .expect(\"generated canonical hex\")"]
    return [
        f"    {type_name}::parse(",
        f"        {const_name},",
        "    )",
        "    .expect(\"generated canonical hex\")",
    ]


def render_generated() -> str:
    catalog = load_source()
    lines: list[str] = []
    lines.append("// @generated by scripts/generate_semantic_contract_catalog.py; DO NOT EDIT.")
    lines.append(f"// Source: {SOURCE_REL}")
    lines.append("//")
    lines.append("// Manifest constants AND derived ID values for the runtime semantic")
    lines.append("// catalog (spec §10). Rust const-evaluation cannot allocate, so the")
    lines.append("// derived ID VALUES are checked in as canonical hex string constants")
    lines.append("// and materialized deterministically through parse() accessors (no")
    lines.append("// lazy statics — spec §10 bans hidden process state). The recompute KAT")
    lines.append("// (semantic_catalog_kat.rs) re-derives every ID from these constants")
    lines.append("// via the §9 persistence functions and fails the build on drift.")
    lines.append("// Hand-editing any constant is a gate violation.")
    lines.append("#![allow(dead_code)] // consumed by the KAT now and the Task-8 runtime later")
    lines.append("")
    lines.append("use mtgml_model::{RulesContractIdV1, SemanticContractIdV1};")
    lines.append("")
    for entry in catalog["entries"]:
        if not isinstance(entry, dict):
            raise SystemExit("catalog entry must be an object")
        entry_id = entry["entry_id"]
        if not isinstance(entry_id, str) or not entry_id:
            raise SystemExit("catalog entry_id must be a non-empty string")
        rules_id, semantic_id = derive_ids(entry)
        recorded_rules = entry["rules_contract_id"]
        recorded_semantic = entry["semantic_contract_id"]
        if recorded_rules != rules_id or recorded_semantic != semantic_id:
            raise SystemExit(
                f"catalog source ID drift for entry {entry_id!r}: recorded IDs do not "
                "recompute from the manifest facts via the Task-2 mirrors"
            )
        snake = entry_id.replace("-", "_")
        const_prefix = f"SEMANTIC_CONTRACT_CATALOG_{snake.upper()}"
        authority = entry["rules_authority"]
        if not isinstance(authority, dict) or authority.get("variant") != "synthetic_legacy":
            raise SystemExit(
                f"catalog entry {entry_id!r}: only synthetic_legacy entries are "
                "supported by this generator version"
            )
        if entry["capability_closure"] is not None:
            raise SystemExit(
                f"catalog entry {entry_id!r}: capability_closure must be null for "
                "synthetic_legacy entries"
            )
        if entry["format_contract_id"] is not None or entry["content_contract_id"] is not None:
            raise SystemExit(
                f"catalog entry {entry_id!r}: format/content dimensions must be null "
                "in the V5 slice"
            )
        lines.append(f"// {entry_id}")
        lines.append(f"pub const {const_prefix}_RULES_CONTRACT_HEX: &str =")
        lines.append(f"    \"{rules_id}\";")
        lines.append(f"pub const {const_prefix}_SEMANTIC_CONTRACT_HEX: &str =")
        lines.append(f"    \"{semantic_id}\";")
        lines.append("")
        lines.append(f"pub fn {snake}_rules_contract_id() -> RulesContractIdV1 {{")
        lines.extend(
            parse_call_lines(
                "RulesContractIdV1",
                f"{const_prefix}_RULES_CONTRACT_HEX",
            )
        )
        lines.append("}")
        lines.append("")
        lines.append(f"pub fn {snake}_semantic_contract_id() -> SemanticContractIdV1 {{")
        lines.extend(
            parse_call_lines(
                "SemanticContractIdV1",
                f"{const_prefix}_SEMANTIC_CONTRACT_HEX",
            )
        )
        lines.append("}")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def generated_bytes(content: str) -> bytes:
    return content.encode("utf-8")


def write_generated(target: Path, content: str) -> None:
    target.write_bytes(generated_bytes(content))


def generated_bytes_match(target: Path, content: str) -> bool:
    return target.is_file() and target.read_bytes() == generated_bytes(content)


def check_paths(targets: list[Path]) -> int:
    content = render_generated()
    drift = [str(target) for target in targets if not generated_bytes_match(target, content)]
    if drift:
        print("generated semantic-contract catalog drift:")
        for rel in drift:
            print(f"  - {rel}")
        return 1
    return 0


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    if args.check:
        return check_paths([TARGET_PATH])
    TARGET_PATH.parent.mkdir(parents=True, exist_ok=True)
    write_generated(TARGET_PATH, render_generated())
    print(f"PASS: semantic-contract catalog generated to {TARGET_REL}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
