// @generated by scripts/generate_semantic_contract_catalog.py; DO NOT EDIT.
// Source: contracts/catalog/semantic-contracts.v1.json
//
// Runtime execution-profile mapping for MagicRules.
// Derived from the same catalog source and mechanical
// generation path as semantic_catalog_generated.rs.
// Do not manually maintain hex constants — single source.
#![allow(dead_code)] // consumed by KAT and Task-8 runtime later

use mtgml_model::{
    ExecutionProgramV1, RulesContractIdV1, SemanticContractIdV1, SemanticContractManifestV1,
};

pub const MAGIC_TURN_STRUCTURE_SEMANTIC_CONTRACT_HEX: &str =
    "7e8f54f15bd27d16643422f6904a23ea2004cab1098b56f8cd842a2397ff42fe";

pub const MAGIC_TURN_STRUCTURE_RULES_CONTRACT_HEX: &str =
    "92377633765924893ad9ca0102a07cdf2a8730526909b7d7b5e3059ae4487065";

pub const SYNTHETIC_LEGACY_SEMANTIC_CONTRACT_HEX: &str =
    "66ccac959475370e641e853473cbdd7f88489399587794b43f66cfa0342b1be4";

pub fn magic_turn_structure_0_1_0_semantic_contract_id() -> SemanticContractIdV1 {
    SemanticContractIdV1::parse(MAGIC_TURN_STRUCTURE_SEMANTIC_CONTRACT_HEX)
        .expect("generated canonical hex")
}

pub fn magic_turn_structure_0_1_0_rules_contract_id() -> RulesContractIdV1 {
    RulesContractIdV1::parse(MAGIC_TURN_STRUCTURE_RULES_CONTRACT_HEX)
        .expect("generated canonical hex")
}

pub(crate) struct MagicExecutionProfile {
    admitted_contract: SemanticContractIdV1,
    turn_structure_0_1_0: bool,
}

impl MagicExecutionProfile {
    pub(crate) fn allows_turn_structure_0_1_0(&self) -> bool {
        self.turn_structure_0_1_0
    }
    pub(crate) fn admitted_contract(&self) -> &SemanticContractIdV1 {
        &self.admitted_contract
    }
}

#[cfg(test)]
pub(crate) fn test_only_magic_execution_profile(
    admitted_contract: SemanticContractIdV1,
    turn_structure_0_1_0: bool,
) -> MagicExecutionProfile {
    MagicExecutionProfile {
        admitted_contract,
        turn_structure_0_1_0,
    }
}

pub fn magic_execution_profile(
    semantic_contract_id: SemanticContractIdV1,
) -> Option<MagicExecutionProfile> {
    let admitted = magic_turn_structure_0_1_0_semantic_contract_id();
    if semantic_contract_id == admitted {
        Some(MagicExecutionProfile {
            admitted_contract: semantic_contract_id,
            turn_structure_0_1_0: true,
        })
    } else {
        None
    }
}

pub fn magic_turn_structure_0_1_0_rules_manifest() -> mtgml_model::RulesContractManifestV1 {
    mtgml_model::RulesContractManifestV1 {
        rules_authority: mtgml_model::RulesAuthorityV1::ComprehensiveRules {
            snapshot_id: "wotc-cr-2026-08-07-txt-20260819-sha256-4381ad1b39ab2c05f7d03633a20f711ed37277074d3266dcba5f38cbb527423f".to_owned(),
        },
        capability_closure: Some(vec![
            mtgml_model::CapabilityRequirementV1 {
                key: "rules/turn-structure".to_owned(),
                version: "0.1.0".to_owned(),
            },
        ]),
    }
}

pub fn magic_turn_structure_0_1_0_semantic_manifest() -> SemanticContractManifestV1 {
    mtgml_model::SemanticContractManifestV1 {
        rules_contract_id: magic_turn_structure_0_1_0_rules_contract_id(),
        format_contract_id: None,
        content_contract_id: None,
    }
}

pub fn execution_contract_supported(
    program: ExecutionProgramV1,
    semantic_contract_id: &SemanticContractIdV1,
) -> bool {
    match program {
        ExecutionProgramV1::SyntheticRulesCompat => {
            *semantic_contract_id == synthetic_legacy_default_semantic_contract_id()
        }
        ExecutionProgramV1::MagicRules => {
            magic_execution_profile(semantic_contract_id.clone()).is_some()
        }
    }
}

pub fn synthetic_legacy_default_semantic_contract_id() -> SemanticContractIdV1 {
    SemanticContractIdV1::parse(SYNTHETIC_LEGACY_SEMANTIC_CONTRACT_HEX)
        .expect("generated canonical hex")
}
