// @generated by scripts/generate_semantic_contract_catalog.py; DO NOT EDIT.
// Source: contracts/catalog/semantic-contracts.v1.json
// Exact production Magic execution profiles derived from the semantic catalog.

use mtgml_model::{ExecutionProgramV1, SemanticContractIdV1};

pub(crate) const MAGIC_TURN_STRUCTURE_SEMANTIC_CONTRACT_HEX: &str =
    "7e8f54f15bd27d16643422f6904a23ea2004cab1098b56f8cd842a2397ff42fe";
pub(crate) const MAGIC_S3_A_SEMANTIC_CONTRACT_HEX: &str =
    "51efc0307d9ef8fc4fca46f8ea6e4ea5d5293cb8301c2a7917a590982079020e";
pub(crate) const MAGIC_S3_B_SEMANTIC_CONTRACT_HEX: &str =
    "c480cbae69bf0496aff83bb973a859721bfa0f969351b33b3f0b09ee3f7c5498";
pub(crate) const MAGIC_S3_C_SEMANTIC_CONTRACT_HEX: &str =
    "2818c779c0a1f3b534d5551d9842a26e64ea93fa5906e8d43b499c4a3e042cb5";
pub(crate) const MAGIC_COMBAT_ATTACKERS_SEMANTIC_CONTRACT_HEX: &str =
    "fb55663090b2ea6d0ab709d56a6b58ce3a21b3beca24113008bb98684f3230a7";
pub(crate) const MAGIC_COMBAT_BLOCKERS_SEMANTIC_CONTRACT_HEX: &str =
    "b788155232e2fca4b3f43170251f86dd5718ba42b3b674309d99c1df9eddaa6c";
pub(crate) const MAGIC_COMBAT_DAMAGE_SEMANTIC_CONTRACT_HEX: &str =
    "58c55b0f08f045da01e81c595a00cc63dc75361efeb83be7e5e82064ae85805e";
pub(crate) const MAGIC_BOUNDED_TURN_SEMANTIC_CONTRACT_HEX: &str =
    "b03634245635bb65dffe5f20a21ac47828a44a3aad5732594216b8138c7eee00";
pub(crate) const SYNTHETIC_LEGACY_SEMANTIC_CONTRACT_HEX: &str =
    "66ccac959475370e641e853473cbdd7f88489399587794b43f66cfa0342b1be4";

pub(crate) fn magic_turn_structure_0_1_0_semantic_contract_id() -> SemanticContractIdV1 {
    SemanticContractIdV1::parse(MAGIC_TURN_STRUCTURE_SEMANTIC_CONTRACT_HEX)
        .expect("generated canonical hex")
}
pub(crate) fn magic_s3_a_ordered_sba_0_1_0_semantic_contract_id() -> SemanticContractIdV1 {
    SemanticContractIdV1::parse(MAGIC_S3_A_SEMANTIC_CONTRACT_HEX).expect("generated canonical hex")
}
pub(crate) fn magic_s3_b_basic_priority_0_1_0_semantic_contract_id() -> SemanticContractIdV1 {
    SemanticContractIdV1::parse(MAGIC_S3_B_SEMANTIC_CONTRACT_HEX).expect("generated canonical hex")
}
pub(crate) fn magic_s3_c_draw_interaction_0_1_0_semantic_contract_id() -> SemanticContractIdV1 {
    SemanticContractIdV1::parse(MAGIC_S3_C_SEMANTIC_CONTRACT_HEX).expect("generated canonical hex")
}
pub(crate) fn magic_combat_attackers_0_1_0_semantic_contract_id() -> SemanticContractIdV1 {
    SemanticContractIdV1::parse(MAGIC_COMBAT_ATTACKERS_SEMANTIC_CONTRACT_HEX)
        .expect("generated canonical hex")
}
pub(crate) fn magic_combat_blockers_0_1_0_semantic_contract_id() -> SemanticContractIdV1 {
    SemanticContractIdV1::parse(MAGIC_COMBAT_BLOCKERS_SEMANTIC_CONTRACT_HEX)
        .expect("generated canonical hex")
}
pub(crate) fn magic_combat_damage_0_1_0_semantic_contract_id() -> SemanticContractIdV1 {
    SemanticContractIdV1::parse(MAGIC_COMBAT_DAMAGE_SEMANTIC_CONTRACT_HEX)
        .expect("generated canonical hex")
}
pub(crate) fn magic_bounded_turn_0_1_0_semantic_contract_id() -> SemanticContractIdV1 {
    SemanticContractIdV1::parse(MAGIC_BOUNDED_TURN_SEMANTIC_CONTRACT_HEX)
        .expect("generated canonical hex")
}
pub(crate) fn synthetic_legacy_default_semantic_contract_id() -> SemanticContractIdV1 {
    SemanticContractIdV1::parse(SYNTHETIC_LEGACY_SEMANTIC_CONTRACT_HEX)
        .expect("generated canonical hex")
}

pub(crate) struct MagicExecutionProfile {
    turn_structure_0_1_0: bool,
    state_based_actions_combat_0_1_0: bool,
    basic_priority_0_1_0: bool,
    draw_card_0_1_0: bool,
    combat_phase_0_1_0: bool,
    declare_attackers_0_1_0: bool,
    declare_blockers_0_1_0: bool,
    combat_damage_0_1_0: bool,
    cleanup_reset_0_1_0: bool,
}
impl MagicExecutionProfile {
    pub(crate) fn allows_turn_structure_0_1_0(&self) -> bool {
        self.turn_structure_0_1_0
    }
    pub(crate) fn allows_state_based_actions_combat_0_1_0(&self) -> bool {
        self.state_based_actions_combat_0_1_0
    }
    pub(crate) fn allows_basic_priority_0_1_0(&self) -> bool {
        self.basic_priority_0_1_0
    }
    pub(crate) fn allows_draw_card_0_1_0(&self) -> bool {
        self.draw_card_0_1_0
    }
    pub(crate) fn allows_combat_attackers_0_1_0(&self) -> bool {
        self.combat_phase_0_1_0 && self.declare_attackers_0_1_0
    }
    pub(crate) fn allows_combat_blockers_0_1_0(&self) -> bool {
        self.allows_combat_attackers_0_1_0() && self.declare_blockers_0_1_0
    }
    pub(crate) fn allows_combat_damage_0_1_0(&self) -> bool {
        self.allows_combat_blockers_0_1_0() && self.combat_damage_0_1_0
    }
    pub(crate) fn allows_cleanup_reset_0_1_0(&self) -> bool {
        self.turn_structure_0_1_0 && self.cleanup_reset_0_1_0
    }
    pub(crate) fn is_turn_structure_only_profile(&self) -> bool {
        self.allows_turn_structure_0_1_0()
            && !self.allows_state_based_actions_combat_0_1_0()
            && !self.allows_basic_priority_0_1_0()
            && !self.allows_draw_card_0_1_0()
            && !self.allows_combat_attackers_0_1_0()
            && !self.allows_combat_blockers_0_1_0()
            && !self.allows_combat_damage_0_1_0()
            && !self.allows_cleanup_reset_0_1_0()
    }
}
#[cfg(test)]
pub(crate) fn test_only_magic_execution_profile(
    admitted_contract: SemanticContractIdV1,
    turn_structure_0_1_0: bool,
) -> MagicExecutionProfile {
    MagicExecutionProfile {
        turn_structure_0_1_0: turn_structure_0_1_0
            && admitted_contract == magic_turn_structure_0_1_0_semantic_contract_id(),
        state_based_actions_combat_0_1_0: false,
        basic_priority_0_1_0: false,
        draw_card_0_1_0: false,
        combat_phase_0_1_0: false,
        declare_attackers_0_1_0: false,
        declare_blockers_0_1_0: false,
        combat_damage_0_1_0: false,
        cleanup_reset_0_1_0: false,
    }
}
pub(crate) fn magic_execution_profile(
    semantic_contract_id: SemanticContractIdV1,
) -> Option<MagicExecutionProfile> {
    if semantic_contract_id == magic_turn_structure_0_1_0_semantic_contract_id() {
        return Some(MagicExecutionProfile {
            turn_structure_0_1_0: true,
            state_based_actions_combat_0_1_0: false,
            basic_priority_0_1_0: false,
            draw_card_0_1_0: false,
            combat_phase_0_1_0: false,
            declare_attackers_0_1_0: false,
            declare_blockers_0_1_0: false,
            combat_damage_0_1_0: false,
            cleanup_reset_0_1_0: false,
        });
    }
    if semantic_contract_id == magic_s3_a_ordered_sba_0_1_0_semantic_contract_id() {
        return Some(MagicExecutionProfile {
            turn_structure_0_1_0: true,
            state_based_actions_combat_0_1_0: true,
            basic_priority_0_1_0: false,
            draw_card_0_1_0: false,
            combat_phase_0_1_0: false,
            declare_attackers_0_1_0: false,
            declare_blockers_0_1_0: false,
            combat_damage_0_1_0: false,
            cleanup_reset_0_1_0: false,
        });
    }
    if semantic_contract_id == magic_s3_b_basic_priority_0_1_0_semantic_contract_id() {
        return Some(MagicExecutionProfile {
            turn_structure_0_1_0: true,
            state_based_actions_combat_0_1_0: true,
            basic_priority_0_1_0: true,
            draw_card_0_1_0: false,
            combat_phase_0_1_0: false,
            declare_attackers_0_1_0: false,
            declare_blockers_0_1_0: false,
            combat_damage_0_1_0: false,
            cleanup_reset_0_1_0: false,
        });
    }
    if semantic_contract_id == magic_s3_c_draw_interaction_0_1_0_semantic_contract_id() {
        return Some(MagicExecutionProfile {
            turn_structure_0_1_0: true,
            state_based_actions_combat_0_1_0: true,
            basic_priority_0_1_0: true,
            draw_card_0_1_0: true,
            combat_phase_0_1_0: false,
            declare_attackers_0_1_0: false,
            declare_blockers_0_1_0: false,
            combat_damage_0_1_0: false,
            cleanup_reset_0_1_0: false,
        });
    }
    if semantic_contract_id == magic_combat_attackers_0_1_0_semantic_contract_id() {
        return Some(MagicExecutionProfile {
            turn_structure_0_1_0: true,
            state_based_actions_combat_0_1_0: true,
            basic_priority_0_1_0: true,
            draw_card_0_1_0: true,
            combat_phase_0_1_0: true,
            declare_attackers_0_1_0: true,
            declare_blockers_0_1_0: false,
            combat_damage_0_1_0: false,
            cleanup_reset_0_1_0: false,
        });
    }
    if semantic_contract_id == magic_combat_blockers_0_1_0_semantic_contract_id() {
        return Some(MagicExecutionProfile {
            turn_structure_0_1_0: true,
            state_based_actions_combat_0_1_0: true,
            basic_priority_0_1_0: true,
            draw_card_0_1_0: true,
            combat_phase_0_1_0: true,
            declare_attackers_0_1_0: true,
            declare_blockers_0_1_0: true,
            combat_damage_0_1_0: false,
            cleanup_reset_0_1_0: false,
        });
    }
    if semantic_contract_id == magic_combat_damage_0_1_0_semantic_contract_id() {
        return Some(MagicExecutionProfile {
            turn_structure_0_1_0: true,
            state_based_actions_combat_0_1_0: true,
            basic_priority_0_1_0: true,
            draw_card_0_1_0: true,
            combat_phase_0_1_0: true,
            declare_attackers_0_1_0: true,
            declare_blockers_0_1_0: true,
            combat_damage_0_1_0: true,
            cleanup_reset_0_1_0: false,
        });
    }
    if semantic_contract_id == magic_bounded_turn_0_1_0_semantic_contract_id() {
        return Some(MagicExecutionProfile {
            turn_structure_0_1_0: true,
            state_based_actions_combat_0_1_0: true,
            basic_priority_0_1_0: true,
            draw_card_0_1_0: true,
            combat_phase_0_1_0: true,
            declare_attackers_0_1_0: true,
            declare_blockers_0_1_0: true,
            combat_damage_0_1_0: true,
            cleanup_reset_0_1_0: true,
        });
    }
    None
}
pub fn execution_contract_supported(
    program: ExecutionProgramV1,
    semantic_contract_id: &SemanticContractIdV1,
) -> bool {
    match program {
        ExecutionProgramV1::SyntheticRulesCompat => {
            *semantic_contract_id == synthetic_legacy_default_semantic_contract_id()
        }
        ExecutionProgramV1::MagicRules => {
            magic_execution_profile(semantic_contract_id.clone()).is_some()
        }
    }
}
